"""Calls between a generated Node project's own modules that nothing defines.

The JavaScript half of `pyimports.unresolved_local_calls`, and it exists because
that one is `ast`-based and therefore Python-only — so on the Node stack the
check did not merely weaken, it returned nothing at all while reading exactly as
if the project had passed it.

What that cost, measured on the OpenBazaar PRD build (2026-08-04): generation
rewrote the tail of `server.js` as

    db.setup().then(() => { app.listen(PORT, …); });

`db.js` exports `initDb`, not `setup`. `node --check` accepts it — the call is
syntactically perfect — the route parser finds every route, the boot-block
invariant is satisfied because `app.listen(` is right there, and the answer
reports a clean build. The app then dies on startup with `db.setup is not a
function`, which is the one failure mode nothing else here can see.

Deliberately narrow, in the same three ways the Python version is:

  * **Local modules only.** A name bound by `require("./db")`. Anything from
    `node_modules` is somebody else's API and unreadable from here.
  * **Reported, never repaired.** Writing the missing function means inventing a
    query.
  * **"Cannot tell" is not "absent".** A module whose exports cannot be read
    contributes no complaints, because a confident wrong complaint about a
    working build is worse than a missed one.
"""

from __future__ import annotations

import re

# `const db = require("./db")` / `let models = require('./models.js')`
_REQUIRE_RE = re.compile(
    r"""\b(?:const|let|var)\s+(?P<name>[A-Za-z_$][\w$]*)\s*=\s*"""
    r"""require\(\s*["'`]\./(?P<module>[\w./-]+?)(?:\.js|\.mjs)?["'`]\s*\)""",
)
# `module.exports = { a, b, c }` — the shape every scaffold module uses.
_EXPORTS_BLOCK_RE = re.compile(r"\bmodule\s*\.\s*exports\s*=\s*\{(?P<body>[^}]*)\}")
# `module.exports.foo =` / `exports.foo =`
_EXPORTS_PROP_RE = re.compile(
    r"\b(?:module\s*\.\s*)?exports\s*\.\s*(?P<name>[A-Za-z_$][\w$]*)\s*="
)
# A key in an exports block: `foo` or `foo: bar`.
_EXPORT_KEY_RE = re.compile(r"([A-Za-z_$][\w$]*)\s*(?::|,|$)")


def exported_names(source: str) -> set[str]:
    """Every name a CommonJS module exports. Empty means "could not tell"."""
    text = source or ""
    names: set[str] = set()
    for match in _EXPORTS_BLOCK_RE.finditer(text):
        for line in match.group("body").split(","):
            key = _EXPORT_KEY_RE.match(line.strip())
            if key:
                names.add(key.group(1))
    names.update(m.group("name") for m in _EXPORTS_PROP_RE.finditer(text))
    return names


def fix_db_bootstrap(source: str, db_source: str) -> tuple[str, list[str]]:
    """Repoint the startup call at the schema function `db.js` really exports.

    NOT a general near-miss repair — `setup` and `initDb` are nowhere near each
    other as strings, so no similarity rule would have caught this. It is a
    scaffold INVARIANT, of the same kind as the `/` route: the entry file starts
    the app by awaiting the data layer's one setup function, and `db.js` is
    generated by Coder, so what that function is called is known rather than
    guessed.

    Narrow on purpose. It fires only when the entry file calls exactly one
    unexported function on the `db` module, that call is the one the server
    starts from, and `db.js` exports `initDb`. Anything else is reported by
    `unresolved_local_calls` and left alone.

    Returns ``(source, fixes)``.
    """
    text = source or ""
    exports = exported_names(db_source or "")
    if "initDb" not in exports:
        return source, []
    fixes: list[str] = []
    for match in _REQUIRE_RE.finditer(text):
        if match.group("module").rsplit("/", 1)[-1] != "db":
            continue
        local = match.group("name")
        pattern = re.compile(
            rf"\b({re.escape(local)})\s*\.\s*([A-Za-z_$][\w$]*)\s*\(\s*\)"
        )
        for call in list(pattern.finditer(text)):
            name = call.group(2)
            if name in exports:
                continue
            text = text[: call.start()] + f"{local}.initDb()" + text[call.end() :]
            fixes.append(f"{local}.{name}() -> {local}.initDb()")
            break  # one rewrite per pass; the spans after it have moved
    return (text, fixes) if fixes else (source, [])


def unresolved_local_calls(source: str, module_sources: dict[str, str]) -> list[str]:
    """`["db.setup"]` for calls on a required local module that it never exports.

    ``module_sources`` maps a module's stem (`db`, `models`) to its source, the
    same shape `pyimports.unresolved_local_calls` takes.
    """
    text = source or ""
    out: list[str] = []
    seen: set[str] = set()
    for match in _REQUIRE_RE.finditer(text):
        local = match.group("name")
        stem = match.group("module").rsplit("/", 1)[-1]
        module_source = module_sources.get(stem)
        if module_source is None:
            continue  # not one of ours — nothing to check against
        exports = exported_names(module_source)
        if not exports:
            continue  # could not read them; a guess here would be a false alarm
        call_re = re.compile(
            rf"\b{re.escape(local)}\s*\.\s*(?P<fn>[A-Za-z_$][\w$]*)\s*\("
        )
        for call in call_re.finditer(text):
            name = call.group("fn")
            ref = f"{local}.{name}"
            if name in exports or ref in seen:
                continue
            seen.add(ref)
            out.append(ref)
    return out
